[global]
log_level = 'debug'

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3002

[telemetry.buckets.latency_submitted]
start = 500
end = 20000
buckets = 10

[telemetry.buckets.latency_confirmed]
start = 1000
end = 30000
buckets = 10

[rest]
enabled = false
host = '127.0.0.1'
port = 3030

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[[chains]]
id = 'simd-1'
type = 'CosmosSdk'
compat_mode = '0.37'
rpc_addr = 'http://cosmos:26657'
grpc_addr = 'http://cosmos:9090'
event_source = { mode = 'push', url = 'ws://cosmos:26657/websocket', batch_delay = '200ms' }
rpc_timeout = '10s'
account_prefix = 'cosmos'
key_name = 'relayer'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 5000000
max_gas = 15000000
gas_price = { price = 0.025, denom = 'stake' }
gas_multiplier = 2.0
max_msg_num = 20
max_tx_size = 209715
clock_drift = '20s'
max_block_time = '30s'
trusting_period = '10days'
memo_prefix = ''
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = 'stellar-testnet'
type = 'Stellar'
event_poll_interval = 20
event_replay_window = 256
gateway_url = 'http://gateway:50052'
network_passphrase = 'Test SDF Network ; September 2015'
ibc_contract_id = ''
key_name = 'stellar-relayer'
stub_key_name = 'stellar-relayer'
max_block_time = '6s'
trust_threshold = '2/3'
clear_interval = 0
query_packets_chunk_size = 50
clock_drift = '5s'
client_refresh_rate = '1/3'
wasm_checksum_hex = '3d4fc74efc59d49106857a887c005062829d9cfd5ca560cd664e146460c9ecef'
packet_filter = { policy = 'allow', list = [['transfer', '*']] }

# [[chains]]
# id = 'provider'
# type = 'CosmosSdk'
# compat_mode = '0.37'
# rpc_addr = 'https://rpc.provider-sentry-01.hub-testnet.polypore.xyz'
# grpc_addr = 'https://grpc.provider-sentry-01.hub-testnet.polypore.xyz'
# event_source = { mode = 'push', url = 'wss://rpc.provider-sentry-01.hub-testnet.polypore.xyz/websocket', batch_delay = '500ms' }
# rpc_timeout = '15s'
# account_prefix = 'cosmos'
# key_name = 'relayer'
# address_type = { derivation = 'cosmos' }
# store_prefix = 'ibc'
# default_gas = 5000000
# max_gas = 15000000
# gas_price = { price = 0.025, denom = 'uatom' }
# gas_multiplier = 2.0
# max_msg_num = 20
# max_tx_size = 209715
# clock_drift = '20s'
# max_block_time = '30s'
# trusting_period = '14days'
# memo_prefix = ''
# trust_threshold = { numerator = '1', denominator = '3' }
# packet_filter = { policy = 'allow', list = [['transfer', '*']] }

# [[chains]]
# type = 'Cardano'
# id = 'cardano-devnet'
# gateway_url = 'http://localhost:5001'
# network_id = 0
# key_name = 'cardano-relayer'
# key_store_type = 'Test'  # or 'Memory' for production
# account = 0
# max_block_time = '20000ms'
# clock_drift = '5s'
# mithril_certification_timeout = '30m'
# mithril_poll_interval = '5s'
# mithril_wait_log_interval = '30s'
# trust_threshold = { numerator = '2', denominator = '3' }
