name: interstellar

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: interstellar-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ics02-clients:
    uses: ./.github/workflows/interstellar-ics.yml
    secrets: inherit
    with:
      ics: ics02-clients

  ics02-counterparty:
    uses: ./.github/workflows/interstellar-ics.yml
    secrets: inherit
    with:
      ics: ics02-counterparty

  ics20-transfer:
    uses: ./.github/workflows/interstellar-ics.yml
    secrets: inherit
    with:
      ics: ics20-transfer

  ics02-query:
    uses: ./.github/workflows/interstellar-ics.yml
    secrets: inherit
    with:
      ics: ics02-query
